- name: Playbook for httpd installation in ubuntu
  hosts: ubuntu
  tasks:
  - name: Installation
    apt:
      name: apache2
      state: present
  - name: Enabling and starting
    service:
      name: apache2
      enabled: yes
      state: started

